server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/postgres?useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull&amp;transformedBitIsBoolean=true
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
      cache: false    #页面不加载缓存，修改即时生效

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ntm.boot_mybatis.model

#showSql
logging:
  level:
    com:
      example:
        mapper : debug