server:
  port: 7071

spring:
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/postgres?useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull&amp;transformedBitIsBoolean=true
    driver-class-name: org.postgresql.Driver
  jackson:
      data-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期
  expiration: 3600
  tokenHead: "Bearer"

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ntm.boot_mybatis.model
  config-location: classpath:mybatis-config.xml

#showSql
logging:
  level:
    com.ntm.boot_mybatis:
        mapper : debug